### ISSUE TITLE
Saving And Restoring Expand / Collapse State

### ISSUE THREAD

**Issue by ThorinHanson** [emircanpekyurek/ExpandableRecyclerView#1]
Is there a way to maintain the expand/collapse state?

**Comment by emircanpekyurek** [comment]
update the library version to 1.0.5
Added keepExpandCollapseState attribute. Default value is true. You can set it to false if you want in ExpandableRecyclerView xml

**Comment by ThorinHanson** [comment]
Thank you for adding that, but the save state does not persist when navigating away and back.  Additionally, it does not persist upon screen rotation, even in your demo.

**Comment by emircanpekyurek** [comment]
added onSaveInstanceState method to 1.0.6 version
